/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAOs.DeusesDAO;
import Models.DeusesModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chxse
 */
public class PalacioDeuses extends javax.swing.JFrame {

    /**
     * Creates new form PalacioDeuses
     */
    public PalacioDeuses() {
        initComponents();
        CriacaoDeuses();
        ListarDeuses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeDeuses = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescricaoDeuses = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPoderDeuses = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeuses = new javax.swing.JTable();
        btnCriar = new javax.swing.JButton();
        btnEsva = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnSL = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnDeletar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDeuses = new javax.swing.JMenu();
        menuHerois = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaDeuses");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Area de criação de Deuses");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Olimpio");

        jLabel3.setText("Nome:");

        jLabel4.setText("Descricao:");

        jLabel5.setText("Poderes:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pilar02.png"))); // NOI18N

        tblDeuses.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));
        tblDeuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID","Nome", "Descricao", "Poder"
            }
        ));
        jScrollPane1.setViewportView(tblDeuses);

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnEsva.setText("Limpar Campos");
        btnEsva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaActionPerformed(evt);
            }
        });

        jLabel7.setText("ID:");

        btnSL.setText("Selecao de linha");
        btnSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSLActionPerformed(evt);
            }
        });

        txtID.setEditable(false);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(66, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDescricaoDeuses, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPoderDeuses, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNomeDeuses, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(136, 136, 136)
                                .addComponent(jLabel6)))
                        .addGap(199, 199, 199))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnCriar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSL)
                        .addGap(18, 18, 18)
                        .addComponent(btnEsva)
                        .addGap(207, 207, 207)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNomeDeuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDescricaoDeuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPoderDeuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCriar)
                            .addComponent(btnSL)
                            .addComponent(btnDeletar)
                            .addComponent(btnEsva))))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        menuDeuses.setText("Deuses");
        menuDeuses.setEnabled(false);
        jMenuBar1.add(menuDeuses);

        menuHerois.setText("Herois");
        menuHerois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHeroisMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHerois);

        jMenu4.setText("Monstros");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Titans");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Mitos");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        TemploPrincipal tp = new TemploPrincipal();

        tp.setVisible(true);

        dispose();

    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed

        CriacaoDeuses();
        ListarDeuses();

    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEsvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaActionPerformed
        EsvaziarCampos();
    }//GEN-LAST:event_btnEsvaActionPerformed

    private void btnSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSLActionPerformed
        CarregarColunas();
    }//GEN-LAST:event_btnSLActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        DeletarDeuses();
        ListarDeuses();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void menuHeroisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHeroisMouseClicked

        HeroisSec hs = new HeroisSec();
        hs.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_menuHeroisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PalacioDeuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PalacioDeuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PalacioDeuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PalacioDeuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PalacioDeuses().setVisible(true);
            }
        });
    }

    private void CriacaoDeuses() {

        DeusesModel dm = new DeusesModel();

        String nomee = txtNomeDeuses.getText();
        String descricaoo = txtDescricaoDeuses.getText();
        String poderr = txtPoderDeuses.getText();

        if (nomee.isEmpty() && descricaoo.isEmpty() && poderr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else {

            dm.setNome_deuses(nomee);
            dm.setDescricao_deuses(descricaoo);
            dm.setPoder(poderr);

            DeusesDAO ddao = new DeusesDAO();
            ddao.CriarDeuses(dm);

            JOptionPane.showMessageDialog(null, "Deus(a) criado(a) com sucesso!");

            ListarDeuses();

        }
    }

    private void ListarDeuses() {

        try {

            DeusesDAO ddao = new DeusesDAO();

            DefaultTableModel tableModel = (DefaultTableModel) tblDeuses.getModel();

            tableModel.setNumRows(0);

            for (DeusesModel dm : ddao.MostrarDeuses()) {

                tableModel.addRow(new Object[]{
                    dm.getId_deuses(),
                    dm.getNome_deuses(),
                    dm.getDescricao_deuses(),
                    dm.getPoder(),});

                ddao.MostrarDeuses();
            }

        } catch (Exception e) {

            System.out.println("erro em mostrar Deuses: " + e);

        }

    }

    public void DeletarDeuses() {

        try {

            int id = Integer.parseInt(txtID.getText());

            DeusesModel dm = new DeusesModel();

            dm.setId_deuses(id);

            DeusesDAO ddao = new DeusesDAO();
            ddao.DeletarDeuses(id);

            JOptionPane.showMessageDialog(null, "Deus(a) deletado(a) com sucesso!");

        } catch (NumberFormatException e) {
            System.out.println("O texto em txtID não é um número válido.");
        }

    }

    private void CarregarColunas() {
        // Selecionando a linha da tabela
        int carregar = tblDeuses.getSelectedRow();

        if (carregar < 0) {
            JOptionPane.showMessageDialog(null, "Ops! voce nao selecionou nenhuma linha");
        } else {
            txtID.setText(tblDeuses.getModel().getValueAt(carregar, 0).toString());
            txtNomeDeuses.setText(tblDeuses.getModel().getValueAt(carregar, 1).toString());
            txtDescricaoDeuses.setText(tblDeuses.getModel().getValueAt(carregar, 2).toString());
            txtPoderDeuses.setText(tblDeuses.getModel().getValueAt(carregar, 3).toString());
        }
    }

    private void EsvaziarCampos() {
        txtID.setText("");
        txtNomeDeuses.setText("");
        txtDescricaoDeuses.setText("");
        txtPoderDeuses.setText("");

        txtNomeDeuses.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEsva;
    private javax.swing.JButton btnSL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuDeuses;
    private javax.swing.JMenu menuHerois;
    private javax.swing.JTable tblDeuses;
    private javax.swing.JTextField txtDescricaoDeuses;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNomeDeuses;
    private javax.swing.JTextField txtPoderDeuses;
    // End of variables declaration//GEN-END:variables
}
